Skillfactory.Module32.MVCStartWebApp/Models/Db/Request.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Skillfactory.Module32.MVCStartWebApp;

[Table("Requests")]
public class Request
{
	public Guid Id { get; set; }
	public DateTime Date { get; set; }
	public string Url { get; set; }
}

Skillfactory.Module32.MVCStartWebApp/Models/Db/User.cs
namespace Skillfactory.Module32.MVCStartWebApp;
public class User
{
    public Guid Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public DateTime JoinDate { get; set; }
}

Skillfactory.Module32.MVCStartWebApp/Models/Db/UserPost.cs
namespace Skillfactory.Module32.MVCStartWebApp;
public class UserPost
{
    public Guid Id { get; set; }
    public DateTime Date { get; set; }
    public string Title { get; set; }
    public string Text { get; set; }
    public Guid UserId { get; set; }
    public User User { get; set; }
}

Skillfactory.Module32.MVCStartWebApp/Models/ErrorViewModel.cs
namespace Skillfactory.Module32.MVCStartWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Skillfactory.Module32.MVCStartWebApp/Models/Feedback.cs
namespace Skillfactory.Module32.MVCStartWebApp.Models;

public class Feedback
{
    public string From { get; set; }
    public string Text { get; set; }
}

Skillfactory.Module32.MVCStartWebApp/Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Mvc;
using Skillfactory.Module32.MVCStartWebApp.Models;
using System.Diagnostics;

namespace Skillfactory.Module32.MVCStartWebApp.Controllers;

public class FeedbackController : Controller
{
    /// <summary>
    ///  Метод, возвращающий страницу с отзывами
    /// </summary>
    [HttpGet]
    public IActionResult Add()
    {
        return View();
    }

    /// <summary>
    /// Метод для Ajax-запросов
    /// </summary>
    [HttpPost]
    public IActionResult Add(Feedback feedback)
    {
        return StatusCode(200, $"{feedback.From}, спасибо за отзыв!");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Skillfactory.Module32.MVCStartWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Skillfactory.Module32.MVCStartWebApp.Models;
using System.Diagnostics;

namespace Skillfactory.Module32.MVCStartWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Skillfactory.Module32.MVCStartWebApp/Controllers/LogsController.cs
using Microsoft.AspNetCore.Mvc;
using Skillfactory.Module32.MVCStartWebApp.Models;
using System.Diagnostics;

namespace Skillfactory.Module32.MVCStartWebApp.Controllers;

public class LogsController : Controller
{
	private readonly ILogger<LogsController> _logger;
	private readonly IRequestsRepository _repository;

	public LogsController(ILogger<LogsController> logger, IRequestsRepository repository)
    {
		_logger = logger;
		_repository = repository;
	}

    public async Task<IActionResult> Index()
    {
        var requests = await _repository.GetAllRequests();
        return View(requests);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Skillfactory.Module32.MVCStartWebApp/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Skillfactory.Module32.MVCStartWebApp.Models;
using System.Diagnostics;

namespace Skillfactory.Module32.MVCStartWebApp.Controllers;

public class UsersController : Controller
{
    private readonly ILogger<UsersController> _logger;
    private readonly IBlogRepository _repository;

    public UsersController(ILogger<UsersController> logger, IBlogRepository repository)
    {
        _logger = logger;
        _repository = repository;
    }

    public IActionResult Register()
    {
        // Добавим создание нового пользователя
        var newUser = new User()
        {
            Id = Guid.NewGuid(),
        };

        return View(newUser);
    }
    [HttpPost]
    public async Task<IActionResult> Register(User newUser)
    {
        newUser.JoinDate = DateTime.Now;

        // Validate and save the user data to a data source
        if (ModelState.IsValid)
        {
            await _repository.AddUser(newUser);
            Console.WriteLine($"New User Created: {newUser.FirstName} {newUser.LastName}, Join Date: {newUser.JoinDate}");
            return RedirectToAction("UserAdded");
        }

        return View(newUser); // If model validation fails, return to the form with errors
    }
    public async Task<IActionResult> Index()
    {
        var authors = await _repository.GetUsers();
        return View(authors);
    }
    public IActionResult UserAdded()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Skillfactory.Module32.MVCStartWebApp/Views/Feedback/Add.cshtml
@{
	ViewData["Title"] = "View project authors";
}

<style>
	table {
		border-spacing: 0 15px;
		align-self: center;
	}

	th {
		background-color: #4287f5;
		color: white;
	}

	th,
	td {
		width: 150px;
		text-align: center;
		border: none;
		padding: 5px;
	}

	h2 {
		color: #4287f5;
	}

	.submit-button {
		position: absolute;
		margin-left: 140px;
	}
</style>

<div id="main-block" class="text-center">
	<div>
		<h3 style="text-align: left">Оставьте отзыв о проекте здесь</h3>
		<br>
		<table>
			<tr>
				<td>Ваше имя</td>
				<td><input type="text" name="From" /> </td>
			</tr>
			<tr>
				<td>Ваш отзыв</td>
				<td><input type="text" name="Text" /></td>
			</tr>
		</table>
		<br>
		<div class="submit-button">
			<input type="submit" value="Отправить" onclick="ProcessForm()" />
		</div>
		<br>
	</div>
</div>

<script>
 
function ProcessForm(){
   // Инициализация объекта формы
   let data = new FormData();
  
   // Вытаскиваем информацию из полей на странице и добавляем в объект формы
   data.set("From", document.querySelector('[name="From"]').value)
   data.set("Text", document.querySelector('[name="Text"]').value)
  
   // создаем объект запроса
   let postRequest = new XMLHttpRequest();
   postRequest.open('POST', document.URL, true ); /* true = запрос будет выполнен асинхронно */
  
   // посылаем запрос
   postRequest.send(data);
  
    // Функция - обработчик результата с сервера
    postRequest.onload =  function () {
        // сохраняем ответ сервера. не лишним будет также добавить проверку на успешный запрос
        let serverMessage = this.response;
       
       /* Код ниже изменяет значение формы */
      
       // Находим контейнер
       let element = document.getElementById("main-block");
       // Удаляем вложенный контейнер с формой
       element.children[0].remove();
      
       // Создаем новый элемент
       let paragraph = document.createElement("h5");
       // Добавляем ему стиль
       paragraph.style = "text-align : center"
       // Сохраняем в него сообщение сервера
       paragraph.innerText = serverMessage;
      
       // Добавляем дочерные элементы на страницу
       element.appendChild(document.createElement("br"))
       element.appendChild(paragraph)
   };
}
 
</script>

Skillfactory.Module32.MVCStartWebApp/Views/Home/Authors.cshtml
@{
   ViewData["Title"] = "View project authors";
}
 
<style>
     table {
       border-spacing: 0 15px;
       align-self: center;
     }
     th {
       background-color: #4287f5;
       color: white;
     }
     th,
     td {
       width: 150px;
       text-align: center;
       border: 1px solid black;
       padding: 5px;
     }
     h2 {
       color: #4287f5;
     }
   </style>
 
<div class="text-center">
   <h2 class="display-4" style="text-align: left">Пользователи проекта</h2>
   <br>
       <table>
           <tr>
               <td>Идентификатор</td>
               <td>Имя</td>
               <td>Дата регистрации</td>
           </tr>
           @foreach (User user in Model)
               {
               <tr>
                   <td>@user.Id</td>
                   <td>@user.FirstName</td>
                   <td>@user.JoinDate</td>
               </tr>
           }
       </table>
</div>

Skillfactory.Module32.MVCStartWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Skillfactory.Module32.MVCStartWebApp/Views/Logs/Index.cshtml
@{
   ViewData["Title"] = "Requests to server";
}
 
<style>
     table {
       border-spacing: 0 15px;
       align-self: center;
     }
     th {
       background-color: #4287f5;
       color: white;
     }
     th,
     td {
       width: 150px;
       text-align: center;
       border: 1px solid black;
       padding: 5px;
     }
     h2 {
       color: #4287f5;
     }
   </style>
 
<div class="text-center">
   <h2 class="display-4" style="text-align: left">Logs</h2>
   <br>
       <table>
           <tr>
               <td>Date</td>
               <td>Url</td>
           </tr>
           @foreach (Request request in Model)
               {
               <tr>
                   <td>@request.Date</td>
                   <td>@request.Url</td>
               </tr>
           }
       </table>
</div>

Skillfactory.Module32.MVCStartWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Skillfactory.Module32.MVCStartWebApp</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Skillfactory.Module32.MVCStartWebApp.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Skillfactory.Module32.MVCStartWebApp</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Authors</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Register">Sign up</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Feedback" asp-action="Add">Contact us</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - Skillfactory.Module32.MVCStartWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Skillfactory.Module32.MVCStartWebApp/Views/Users/Index.cshtml
@{
   ViewData["Title"] = "View project authors";
}
 
<style>
     table {
       border-spacing: 0 15px;
       align-self: center;
     }
     th {
       background-color: #4287f5;
       color: white;
     }
     th,
     td {
       width: 150px;
       text-align: center;
       border: 1px solid black;
       padding: 5px;
     }
     h2 {
       color: #4287f5;
     }
   </style>
 
<div class="text-center">
   <h2 class="display-4" style="text-align: left">Пользователи проекта</h2>
   <br>
       <table>
           <tr>
               <td>Идентификатор</td>
               <td>Имя</td>
               <td>Дата регистрации</td>
           </tr>
           @foreach (User user in Model)
               {
               <tr>
                   <td>@user.Id</td>
                   <td>@user.FirstName</td>
                   <td>@user.JoinDate</td>
               </tr>
           }
       </table>
</div>

Skillfactory.Module32.MVCStartWebApp/Views/Users/Register.cshtml
@model User

<h2>Registration info</h2>
<form asp-action="Register" method="post">
	<div class="form-group">
		<label asp-for="FirstName">
			First Name
			<input asp-for="FirstName" class="form-control" />
		</label>
	</div>
	<div class="form-group">
		<label asp-for="LastName">
			Last Name
			<input asp-for="LastName" class="form-control" />
		</label>
	</div>
	<button type="submit" class="btn btn-primary">
		Create
	</button>
</form>

Skillfactory.Module32.MVCStartWebApp/Views/Users/UserAdded.cshtml
<p>
	Thank you for signing up!
</p>